# Generated by Django 3.0.4 on 2020-03-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strumming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gig', models.CharField(choices=[('P', 'Practice'), ('C', 'Concert'), ('S', 'Studio')], default='P', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Guitar')),
            ],
        ),
    ]
