# Generated by Django 3.0.4 on 2020-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_strumming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speakers', models.CharField(max_length=20)),
                ('watts', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='strumming',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='strumming',
            name='date',
            field=models.DateField(verbose_name='strumming date'),
        ),
    ]
