# Generated by Django 3.0.4 on 2020-03-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200320_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='amps',
            field=models.ManyToManyField(to='main_app.Amp'),
        ),
    ]
